# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{auto_hash}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kevin Swope"]
  s.date = %q{2010-08-14}
  s.description = %q{A Ruby on Rails plugin to automate hashing an activerecord field using bcrypt; an activerecord wrapper for bcrypt-ruby}
  s.email = %q{gems-kevdev@snkmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.html",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "auto_hash.gemspec",
     "created.rid",
     "init.rb",
     "lib/auto_hash.rb",
     "test/common/user_test.rb",
     "test/rails2x_root/Rakefile",
     "test/rails2x_root/app/controllers/application_controller.rb",
     "test/rails2x_root/app/helpers/application_helper.rb",
     "test/rails2x_root/app/models/user.rb",
     "test/rails2x_root/config/boot.rb",
     "test/rails2x_root/config/database.yml",
     "test/rails2x_root/config/environment.rb",
     "test/rails2x_root/config/environments/development.rb",
     "test/rails2x_root/config/environments/production.rb",
     "test/rails2x_root/config/environments/test.rb",
     "test/rails2x_root/config/initializers/backtrace_silencers.rb",
     "test/rails2x_root/config/initializers/cookie_verification_secret.rb",
     "test/rails2x_root/config/initializers/inflections.rb",
     "test/rails2x_root/config/initializers/mime_types.rb",
     "test/rails2x_root/config/initializers/new_rails_defaults.rb",
     "test/rails2x_root/config/initializers/session_store.rb",
     "test/rails2x_root/config/locales/en.yml",
     "test/rails2x_root/config/routes.rb",
     "test/rails2x_root/db/development.sqlite3",
     "test/rails2x_root/db/migrate/20100803040436_create_users.rb",
     "test/rails2x_root/db/schema.rb",
     "test/rails2x_root/db/seeds.rb",
     "test/rails2x_root/db/test.sqlite3",
     "test/rails2x_root/script/about",
     "test/rails2x_root/script/console",
     "test/rails2x_root/script/dbconsole",
     "test/rails2x_root/script/destroy",
     "test/rails2x_root/script/generate",
     "test/rails2x_root/script/performance/benchmarker",
     "test/rails2x_root/script/performance/profiler",
     "test/rails2x_root/script/plugin",
     "test/rails2x_root/script/runner",
     "test/rails2x_root/script/server",
     "test/rails2x_root/test/test_helper.rb",
     "test/rails2x_root/test/unit/user_test.rb",
     "test/rails3x_root/.gitignore",
     "test/rails3x_root/Gemfile",
     "test/rails3x_root/Gemfile.lock",
     "test/rails3x_root/Rakefile",
     "test/rails3x_root/app/controllers/application_controller.rb",
     "test/rails3x_root/app/helpers/application_helper.rb",
     "test/rails3x_root/app/models/user.rb",
     "test/rails3x_root/app/views/layouts/application.html.erb",
     "test/rails3x_root/config/application.rb",
     "test/rails3x_root/config/boot.rb",
     "test/rails3x_root/config/database.yml",
     "test/rails3x_root/config/environment.rb",
     "test/rails3x_root/config/environments/development.rb",
     "test/rails3x_root/config/environments/production.rb",
     "test/rails3x_root/config/environments/test.rb",
     "test/rails3x_root/config/initializers/backtrace_silencers.rb",
     "test/rails3x_root/config/initializers/inflections.rb",
     "test/rails3x_root/config/initializers/mime_types.rb",
     "test/rails3x_root/config/initializers/secret_token.rb",
     "test/rails3x_root/config/initializers/session_store.rb",
     "test/rails3x_root/config/locales/en.yml",
     "test/rails3x_root/config/routes.rb",
     "test/rails3x_root/db/migrate/20100804020911_create_users.rb",
     "test/rails3x_root/db/schema.rb",
     "test/rails3x_root/db/seeds.rb",
     "test/rails3x_root/script/rails",
     "test/rails3x_root/test/test_helper.rb",
     "test/rails3x_root/test/unit/user_test.rb"
  ]
  s.homepage = %q{http://github.com/kswope/auto_hash}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Ruby on Rails plugin to automate hashing an activerecord field using bcrypt; an activerecord wrapper for bcrypt-ruby}
  s.test_files = [
    "test/common/user_test.rb",
     "test/rails2x_root/app/controllers/application_controller.rb",
     "test/rails2x_root/app/helpers/application_helper.rb",
     "test/rails2x_root/app/models/user.rb",
     "test/rails2x_root/config/boot.rb",
     "test/rails2x_root/config/environment.rb",
     "test/rails2x_root/config/environments/development.rb",
     "test/rails2x_root/config/environments/production.rb",
     "test/rails2x_root/config/environments/test.rb",
     "test/rails2x_root/config/initializers/backtrace_silencers.rb",
     "test/rails2x_root/config/initializers/cookie_verification_secret.rb",
     "test/rails2x_root/config/initializers/inflections.rb",
     "test/rails2x_root/config/initializers/mime_types.rb",
     "test/rails2x_root/config/initializers/new_rails_defaults.rb",
     "test/rails2x_root/config/initializers/session_store.rb",
     "test/rails2x_root/config/routes.rb",
     "test/rails2x_root/db/migrate/20100803040436_create_users.rb",
     "test/rails2x_root/db/schema.rb",
     "test/rails2x_root/db/seeds.rb",
     "test/rails2x_root/test/test_helper.rb",
     "test/rails2x_root/test/unit/user_test.rb",
     "test/rails3x_root/app/controllers/application_controller.rb",
     "test/rails3x_root/app/helpers/application_helper.rb",
     "test/rails3x_root/app/models/user.rb",
     "test/rails3x_root/config/application.rb",
     "test/rails3x_root/config/boot.rb",
     "test/rails3x_root/config/environment.rb",
     "test/rails3x_root/config/environments/development.rb",
     "test/rails3x_root/config/environments/production.rb",
     "test/rails3x_root/config/environments/test.rb",
     "test/rails3x_root/config/initializers/backtrace_silencers.rb",
     "test/rails3x_root/config/initializers/inflections.rb",
     "test/rails3x_root/config/initializers/mime_types.rb",
     "test/rails3x_root/config/initializers/secret_token.rb",
     "test/rails3x_root/config/initializers/session_store.rb",
     "test/rails3x_root/config/routes.rb",
     "test/rails3x_root/db/migrate/20100804020911_create_users.rb",
     "test/rails3x_root/db/schema.rb",
     "test/rails3x_root/db/seeds.rb",
     "test/rails3x_root/test/test_helper.rb",
     "test/rails3x_root/test/unit/user_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bcrypt-ruby>, [">= 0"])
    else
      s.add_dependency(%q<bcrypt-ruby>, [">= 0"])
    end
  else
    s.add_dependency(%q<bcrypt-ruby>, [">= 0"])
  end
end

